[pytest]
# Де шукати тести
testpaths = tests

# Які файли вважати тестовими
python_files = test_*.py

# Які класи вважати тестовими
python_classes = Test*

# Які функції вважати тестовими
python_functions = test_*

# Опції за замовчуванням
# -v         = детальний вивід (verbose)
# --tb=short = коротший traceback при помилках
addopts = -v --tb=short